---
- hosts: 
  - Centos 
  # - Ubuntu
  # - Windows
  roles: 
    - LEMP-Stack
    # - MERN-Stack
    # - Win-Wordpres-Stack
    # - Wordpress-Stack
    # - Docker
    # - Docker_Wordpress-Stack