---
# vars file for Docker_Wordpress-Stack
Package:
  - curl
  - wget
  - zip
  - unzip
  - git
  - ca-certificates 
  - lsb-release
  - apt-utils
  - python2
  - python3
  - python3-pip
  
phpmyadmin_version: 5.2.1-fpm
wordpress_version: 6.1.1
mariadb_version: 10.9.5-jammy


mariadb_user: admin
mariadb_pass: P@ssW0rD
mariadb_db: wordpress