---
# handlers file for roles/Wordpress-Stack
- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Restart Mariadb
  service:
    name: mariadb
    state: restarted

- name: Restart php-fpm
  service:
    name: php-fpm
    state: restarted