---
# task for centos
- name: Install all requemants packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
    #update_cache: yes
  with_items: "{{ Yum_packages }}" 

- name: Install Web server packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
    #update_cache: yes
  with_items: "{{ webpackages }}"

- name: Setup Nginx Conf file
  template: 
    src: sites-available/nginx.conf
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx

- name: Moving Nginx Config file
  template:       
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

# - name: Create a public_html directory 
#   ansible.builtin.file:
#     path: /etc/nginx/nginxconfig.io
#     state: directory
#     mode: '0755'
#     owner: root
#     group: root

- name: Additional Nginx Config file
  template:        
    src: nginxconfig.io.zip
    dest: /etc/nginx/nginxconfig.io.zip

- name: Uzip nginxconfig.io file
  ansible.builtin.command:
    cmd:  /etc/nginx/nginxconfig.io.zip 
  notify: Restart Nginx

- name: Remove Additional Nginx Conf File
  ansible.builtin.file:
    path: /etc/nginx/nginxconfig.io.zip
    state: absent

- name: Create a public_html directory 
  ansible.builtin.file:
    path: /var/www/public_html
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data

- name: Enable Firewall
  firewalld:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - '80'
    - '443'
  notify: Reload CentOS Firewall

# - name: Creata a mysql DB for Wordpress
#   community.mysql.mysql_db: