---
# task for centos
- name: Install all requemants packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
    #update_cache: yes
  with_items: "{{ Yum_packages }}" 

- name: Install Web server packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
    #update_cache: yes
  with_items: "{{ webpackages }}"

- name: Setup Nginx Conf file
  template: 
    src: sites-available/nginx.conf
    dest: /etc/nginx/nginx.conf/default
  notify: Restart Nginx

- name: Moving Nginx Config file
  template:       
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

# - name: Create a public_html directory 
#   ansible.builtin.file:
#     path: /etc/nginx/nginxconfig.io
#     state: directory
#     mode: '0755'
#     owner: root
#     group: root

- name: Additional Nginx Config file
  template:        
    src: nginxconfig.io.zip
    dest: /etc/nginx/nginxconfig.io.zip

- name: Uzip nginxconfig.io file
  ansible.builtin.command:
    cmd:  /etc/nginx/nginxconfig.io.zip 
  notify: Restart Nginx

- name: Remove Additional Nginx Conf File
  ansible.builtin.file:
    path: /etc/nginx/nginxconfig.io.zip
    state: absent

- name: Enable Firewall
  firewalld:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - '80'
    - '443'
  notify: Reload CentOS Firewall

- name: Install all requemants packages
  ansible.builtin.pip:
    name: PyMySQL
    state: latest

- name: Configure MySQL root password
  mysql_user: 
    name: root 
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create new MySQL database
  mysql_db: 
    name: "{{ mysql_database }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create new MySQL user
  mysql_user: 
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Grant privileges to new user
  mysql_user: 
    name: "{{ mysql_user }}"
    priv: "{{ mysql_database }}.*:ALL"
    host: '%'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Downloading Wordpress file
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /var/www/wordpress.tar

- name: Unarchive wordpress file
  ansible.builtin.unarchive:
    src: /var/www/wordpress.tar
    dest: /var/www
    remote_src: yes

- name: Move a file name
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php

- name: directory permision
  ansible.builtin.file:
    path: /var/www/wordpress
    mode: '0755'
    owner: nginx
    group: nginx