---
# tasks file for centos.yml and ubuntu.yml
- include: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian'

- include: centos.yml
  when: ansible_facts['os_family'] == 'RedHat'

- include: windows.yml
  when: ansible_facts['os_family'] == 'Windows'